modLoader="javafml"
loaderVersion="[1,)"
license="All Rights Reserved"
issueTrackerURL="https://gitlab.com/tamimbook-group/create_trackworked/-/issues"

[[mods]]
modId="trackworked"
version="1.0.0"
displayName="Create: Trackworked"
description='''
Create x Sable physics tank tracks, wheels and suspension.
A NeoForge 1.21.1 port of Trackwork, rebuilt on the Sable physics engine.
'''

[[mixins]]
config="trackworked.mixins.json"

[[dependencies.trackworked]]
    modId="neoforge"
    type="required"
    versionRange="[21.1.228,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.trackworked]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1]"
    ordering="NONE"
    side="BOTH"

[[dependencies.trackworked]]
    modId="create"
    type="required"
    versionRange="[6.0.10,6.1.0)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.trackworked]]
    modId="sable"
    type="required"
    versionRange="[1.2.2,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.trackworked]]
    modId="flywheel"
    type="required"
    versionRange="[1.0.6,)"
    ordering="AFTER"
    side="CLIENT"

[[dependencies.trackworked]]
    modId="ponder"
    type="required"
    versionRange="[1.0.85,)"
    ordering="AFTER"
    side="CLIENT"
